# Generated by Django 5.0.1 on 2024-01-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='Username')),
                ('email', models.EmailField(max_length=254)),
                ('total_guesses', models.IntegerField()),
                ('total_correct', models.IntegerField()),
                ('most_popular', models.JSONField()),
                ('extra_stats', models.JSONField()),
            ],
        ),
    ]
